//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormForPractic
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_users
    {
        public int id { get; set; }
        public int product_name { get; set; }
        public int user_id { get; set; }
        public decimal price { get; set; }
        public int count { get; set; }
        public decimal sum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual products products { get; set; }
        public virtual users users { get; set; }
    }
}
